### PR TITLE
Bump version to 4.9.1

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Will require porting of https://github.com/ignitionrobotics/ign-gazebo/commit/63a88dc0386e08b3020c98f78c3cf1989ded529a

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libignition-physics-feedstock/pull/16

**Comment by Tobias-Fischer** [comment]
This fails with `fatal error: sdf/ParticleEmitter.hh: No such file or directory` - any ideas @traversaro?

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libsdformat-feedstock/pull/37

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libignition-gazebo-feedstock/pull/7

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@wolfv @traversaro - seems like we need ignition-transport9-log in conda-forge.

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libignition-transport4-feedstock/pull/39

**Comment by Tobias-Fischer** [comment]
Fix #9

**Comment by Tobias-Fischer** [comment]
It seems like proper Windows support has only landed in ign-gazebo5. Will remove building Windows from this PR.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Gosh, that was a pain getting this to work. Finally ready to review @traversaro @wolfv

**Review by traversaro — APPROVED** [review]

**Pull request merged**
