### PR TITLE
Add regression test for issue 4

### PR DESCRIPTION
**Pull request by traversaro**
Add a regression test for https://github.com/conda-forge/libignition-gazebo-feedstock/issues/4 . It should fail as https://github.com/conda-forge/libignition-common-feedstock/pull/36 still needs to be merged.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by diegoferigo** [comment]
@traversaro Do you think it's worth running a real simulation of a very simple world like the following?

```bash
ign gazebo -r -s /path/to/ign-gazebo/examples/worlds/rolling_shapes.sdf
```

Options:

```
  -r                           Run simulation on start.                         

  -s                           Run only the server (headless mode). This        
                               overrides -g, if it is also present.
```

**Comment by traversaro** [comment]
Good idea, but the test environment does not have the examples unless they are installed with ign-gazebo .

**Comment by diegoferigo** [comment]
In my colcon setup, I have the example installed here:

```
/usr/local/src/workspace/install/share/ignition/ignition-gazebo5/worlds/rolling_shapes.sdf
```

**Comment by diegoferigo** [comment]
Btw, for the records, in my local setup after https://github.com/conda-forge/libignition-common-feedstock/pull/36 the simulation starts correctly but it fails after a second or two with the following error, related to ODE. Opening the GUI, I can see the shape start rolling down before the segfault.

<details>
<summary>Error</summary>

```
libignition-common-feedstock/recipe on  fix/macro_path 🅒 /conda  took 4s 
❯ ign gazebo -r -s -v 4 /conda/share/ignition/ignition-gazebo5/worlds/rolling_shapes.sdf 
[Msg] Ignition Gazebo Server v5.0.0
[Msg] Loading SDF world file[/conda/share/ignition/ignition-gazebo5/worlds/rolling_shapes.sdf].
[Dbg] [EntityComponentManager.cc:672] Using components of type [2251689575469537287] / [ign_gazebo_components.World].
[Dbg] [EntityComponentManager.cc:672] Using components of type [13994732549916512682] / [ign_gazebo_components.Name].
[Dbg] [EntityComponentManager.cc:672] Using components of type [12592746352568925681] / [ign_gazebo_components.Gravity].
[Dbg] [EntityComponentManager.cc:672] Using components of type [2188341333082264598] / [ign_gazebo_components.Physics].
[Dbg] [EntityComponentManager.cc:672] Using components of type [13224937992534617849] / [ign_gazebo_components.MagneticField].
[Dbg] [EntityComponentManager.cc:672] Using components of type [3630648173860223239] / [ign_gazebo_components.PhysicsEnginePlugin].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17459188283658606303] / [ign_gazebo_components.RenderEngineServerPlugin].
[Dbg] [EntityComponentManager.cc:672] Using components of type [8705992680619689917] / [ign_gazebo_components.RenderEngineGuiPlugin].
[Dbg] [EntityComponentManager.cc:672] Using components of type [8753193699724811771] / [ign_gazebo_components.Wind].
[Dbg] [EntityComponentManager.cc:672] Using components of type [12173050716021724529] / [ign_gazebo_components.WorldLinearVelocity].
[Dbg] [EntityComponentManager.cc:672] Using components of type [15943768124495574352] / [ign_gazebo_components.WorldLinearVelocitySeed].
[Dbg] [EntityComponentManager.cc:672] Using components of type [3297509811873971798] / [ign_gazebo_components.ParentEntity].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17100615127981600159] / [ign_gazebo_components.Scene].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17605309075052480649] / [ign_gazebo_components.Atmosphere].
[Dbg] [EntityComponentManager.cc:672] Using components of type [8064491505919932473] / [ign_gazebo_components.Level].
[Dbg] [EntityComponentManager.cc:672] Using components of type [2668898242563798256] / [ign_gazebo_components.DefaultLevel].
[Dbg] [EntityComponentManager.cc:672] Using components of type [11371360182141354106] / [ign_gazebo_components.LevelEntityNames].
[Dbg] [Physics.cc:535] Loaded [ignition::physics::dartsim::Plugin] from library [/conda/lib/ign-physics-4/engine-plugins/libignition-physics-dartsim-plugin.so]
[Dbg] [SimulationRunner.cc:839] Loaded system [ignition::gazebo::systems::Physics] for entity [1]
[Msg] Create service on [/world/shapes/create]
[Msg] Remove service on [/world/shapes/remove]
[Msg] Pose service on [/world/shapes/set_pose]
[Msg] Light configuration service on [/world/shapes/light_config]
[Msg] Physics service on [/world/shapes/set_physics]
[Dbg] [SimulationRunner.cc:839] Loaded system [ignition::gazebo::systems::UserCommands] for entity [1]
[Dbg] [SimulationRunner.cc:839] Loaded system [ignition::gazebo::systems::SceneBroadcaster] for entity [1]
[Dbg] [EntityComponentManager.cc:672] Using components of type [4981278897826323946] / [ign_gazebo_components.WorldSdf].
[Dbg] [EntityComponentManager.cc:672] Using components of type [6687176221774458630] / [ign_gazebo_components.Model].
[Dbg] [EntityComponentManager.cc:672] Using components of type [6612894081701502240] / [ign_gazebo_components.Pose].
[Dbg] [EntityComponentManager.cc:672] Using components of type [8546580419506082455] / [ign_gazebo_components.Static].
[Dbg] [EntityComponentManager.cc:672] Using components of type [9712747055438129860] / [ign_gazebo_components.WindMode].
[Dbg] [EntityComponentManager.cc:672] Using components of type [5661073481138181711] / [ign_gazebo_components.SelfCollide].
[Dbg] [EntityComponentManager.cc:672] Using components of type [11683062252779233161] / [ign_gazebo_components.SourceFilePath].
[Dbg] [EntityComponentManager.cc:672] Using components of type [5081358965268446661] / [ign_gazebo_components.Link].
[Dbg] [EntityComponentManager.cc:672] Using components of type [8112400427272910195] / [ign_gazebo_components.Inertial].
[Dbg] [EntityComponentManager.cc:672] Using components of type [16454635107327670381] / [ign_gazebo_components.Visual].
[Dbg] [EntityComponentManager.cc:672] Using components of type [13011964647677164955] / [ign_gazebo_components.CastShadows].
[Dbg] [EntityComponentManager.cc:672] Using components of type [13440282432131634483] / [ign_gazebo_components.Transparency].
[Dbg] [EntityComponentManager.cc:672] Using components of type [5453622280849253520] / [ign_gazebo_components.VisibilityFlags].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17121648710877364109] / [ign_gazebo_components.Geometry].
[Dbg] [EntityComponentManager.cc:672] Using components of type [9853217982010720764] / [ign_gazebo_components.Material].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17938588655714334139] / [ign_gazebo_components.Collision].
[Dbg] [EntityComponentManager.cc:672] Using components of type [9225962031573086509] / [ign_gazebo_components.CollisionElement].
[Dbg] [EntityComponentManager.cc:672] Using components of type [10522242218202596205] / [ign_gazebo_components.CanonicalLink].
[Dbg] [EntityComponentManager.cc:672] Using components of type [17053779755061317520] / [ign_gazebo_components.ModelCanonicalLink].
[Dbg] [EntityComponentManager.cc:672] Using components of type [11536476718181283925] / [ign_gazebo_components.ModelSdf].
[Dbg] [EntityComponentManager.cc:672] Using components of type [3866641186784191835] / [ign_gazebo_components.Light].
[Dbg] [EntityComponentManager.cc:672] Using components of type [9912133897551038435] / [ign_gazebo_components.LightType].
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/shapes/control] and [/world/shapes/playback/control]
[Msg] Serving GUI information on [/world/shapes/gui/info]
[Msg] World [shapes] initialized with [1ms] physics profile.
[Msg] Serving world SDF generation service on [/world/shapes/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:470] Creating PostUpdate worker threads: 2
[Dbg] [SimulationRunner.cc:483] Creating postupdate worker thread (0)
[Msg] Serving scene information on [/world/shapes/scene/info]
[Msg] Serving graph information on [/world/shapes/scene/graph]
[Msg] Serving full state on [/world/shapes/state]
[Msg] Serving full state (async) on [/world/shapes/state_async]
[Msg] Publishing scene information on [/world/shapes/scene/info]
[Msg] Publishing entity deletions on [/world/shapes/scene/deletion]
[Msg] Publishing state changes on [/world/shapes/state]
[Msg] Publishing pose messages on [/world/shapes/pose/info]
[Msg] Publishing dynamic pose messages on [/world/shapes/dynamic_pose/info]

ODE INTERNAL ERROR 1: assertion "aabbBound >= dMinIntExact && aabbBound < dMaxIntExact" failed in collide() [/home/conda/feedstock_root/build_artifacts/libode_1622444053603/work/ode/src/collision_space.cpp:460]
fish: Job 1, 'ign gazebo -r -s -v 4 /conda/...' terminated by signal SIGABRT (Abort)
```

</details>

**Comment by traversaro** [comment]
`libignition-gazebo5` has other problems, see https://github.com/conda-forge/libignition-gazebo-feedstock/issues/14 . For now we do this just for v4: https://github.com/conda-forge/libignition-gazebo-feedstock/pull/13 .

**Comment by diegoferigo** [comment]
The segfault seems to me what I experienced and described in https://github.com/conda-forge/libignition-common-feedstock/pull/36#issuecomment-874879012. After rebuilding the recipe locally with `conda mambabuild`, `libignition-gazebo5` stopped crashing.

**Pull request closed without merging**
