### PR TITLE
Try building win (v5)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@traversaro - is there a way to not build the UNIT_EntityComponentManager_TEST?

**Comment by traversaro** [comment]
> 
> 
> @traversaro - is there a way to not build the UNIT_EntityComponentManager_TEST?

Probably the easiest option is to comment this line with a patch: https://github.com/ignitionrobotics/ign-gazebo/blob/a41cf80049c07977079d0b215398dc4225b63038/src/CMakeLists.txt#L68 .

**Comment by Tobias-Fischer** [comment]
Ok, let's see what happens.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This finally works and is ready for review/merge @traversaro @wolfv :)

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer !

**Pull request merged**
