### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by traversaro**
Enabled by https://github.com/conda-forge/libignition-physics-feedstock/pull/12 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found it was in an excellent condition.

Thanks @conda-forge-linter, you are always too kind.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
We need to backport also https://github.com/ignitionrobotics/ign-gazebo/pull/561 (or wait for a Ignition Gazebo 4.* release).

**Comment by Tobias-Fischer** [comment]
Ah gosh, looks like much more work than I would have expected. Does https://github.com/ignitionrobotics/ign-gazebo/pull/666 apply cleanly? If so, it's easy enough to backport, otherwise let's wait for a new release?

**Comment by wolfv** [comment]
I think we can also do pre-releases if you're interested. There is a way to push to a seperate "rc" channel with conda forge and I believe it's documented.

**Comment by Tobias-Fischer** [comment]
I checked and it doesn't apply cleanly .. shall we wait for the next release, seeing that they seem fairly frequent?

**Comment by traversaro** [comment]
> I checked and it doesn't apply cleanly .. shall we wait for the next release, seeing that they seem fairly frequent?

Yes, I think it is the best thing to do.

**Comment by traversaro** [comment]
Closing for now to avoid confusion on the status.

**Pull request closed without merging**
